const indexUI = {
    // <!-- UI elements go here -->
            
    // <!--Layer 1 bottom most layer-->
    
        // <!-- mats -->
        "left_mat" : {
            "walkable" : true,
            "data-response" : "",
            "src" : "/public/mat/SpikesMatSprite.png",
            "class" : "mat",
            "left": "440px",
            "top": "490px",
            "width": "340px",
            "height": "340px",
        },
        "right_mat" : {
            "walkable" : true,
            "data-response" : "",
            "src" : "/public/mat/SpikesMatSprite.png",
            "class" : "mat",
            "left": "1870px",
            "top": "445px",
            "width": "430px",
            "height": "430px",
        },
    
        // <!-- tables -->
        "table1" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/desk/ComfortDeskSprite_v1.png",
            "class" : "leaf_table_vert",
            "left": "160px",
            "top": "500px",
            "width": "150px",
            "height": "260px",
        },
        "table2" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/desk/ComfortDeskSprite_h.png",
            "class" : "leaf_table_hori",
            "left": "1935px",
            "top": "960px",
            "width": "260px",
            "height": "150px",
        },
        "table3" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/desk/ComfortDeskSprite_h.png",
            "class" : "leaf_table_hori",
            "left": "2270px",
            "top": "950px",
            "width": "260px",
            "height": "150px",
        },
        "table4" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/desk/ComfortDeskSprite_v.png",
            "class" : "leaf_table_vert",
            "left": "2430px",
            "top": "660px",
            "width": "150px",
            "height": "260px",
        },

        // <!-- boards and posters -->
        "main_bb" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/board/BoardSprite_v.png",
            "class" : "board",
            "left": "945px",
            "top": "5px",
            "width": "550px",
            "height": "150px",
        },
        "peri_bb1" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/board/BoardSprite_v.png",
            "class" : "board",
            "left": "1630px",
            "top": "400px",
            "width": "100px",
            "height": "265px",
        },
        "peri_bb2" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/board/BoardSprite_v.png",
            "class" : "board",
            "left": "1630px",
            "top": "680px",
            "width": "100px",
            "height": "265px",
        },
        "ak47_1" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/csgo_materials/ak47_1.png",
            "class" : "guns",
            "left": "175px",
            "top": "15px",
            "width": "320px",
            "height": "100px",
        },
        "ak47_2" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/csgo_materials/ak47_2.png",
            "class" : "guns",
            "left": "550px",
            "top": "15px",
            "width": "320px",
            "height": "100px",
        },
        "m4a1_1" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/csgo_materials/m4a1_1.jpg",
            "class" : "guns",
            "left": "1625px",
            "top": "15px",
            "width": "320px",
            "height": "100px",
        },
        "m4a1_2" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/csgo_materials/m4a1_2.jpg",
            "class" : "guns",
            "left": "2000px",
            "top": "15px",
            "width": "320px",
            "height": "100px",
        },

        
        // <!-- Finally welcome mat, hello sign and exit -->
        "hello_sign" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/sign2.gif",
            "class" : "sign",
            "left" : "1200px",
            "top" : "888px",
            "width" : "93px",
            "height" : "63px"
        },
        "welcome_mat" : {
            "walkable" : true,
            "data-response" : "",
            "src" : "/public/pokemon_resources/welcome_mat.png",
            "class" : "mat",
            "left": "1300px",
            "top": "1010px",
            "width": "126px",
            "height": "70px",
        },
        // "exit" : {
        //     "walkable" : true,
        //     "data-response" : "",
        //     "src" : "/public/pokemon_resources/exit.png",
        //     "class" : "exit"
        // },
    
    
    // <!-- layer 2 -->

        // <!-- on table stuff, dolls, books -->
        "pikachu" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/dolls/Doll_Pikachu_III.png",
            "class" : "dolls",
            "left": "150px",
            "top": "528px",
            "width": "105px",
            "height": "105px",
        },
        "togepi" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/dolls/Doll_Togepi_III.png",
            "class" : "dolls",
            "left": "150px",
            "top": "640px",
            "width": "105px",
            "height": "105px",
        },
        "book1" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/book_v.png",
            "class" : "book_v",
            "left": "1975px",
            "top": "965px",
            "width": "90px",
            "height": "105px",
        },
        "book2" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/book_v.png",
            "class" : "book_v",
            "left": "2095px",
            "top": "965px",
            "width": "90px",
            "height": "105px",
        },
        "book3" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/book_v.png",
            "class" : "book_v",
            "left": "2300px",
            "top": "965px",
            "width": "90px",
            "height": "105px",
        },
        "book4" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/book_v.png",
            "class" : "book_v",
            "left": "2435px",
            "top": "965px",
            "width": "90px",
            "height": "105px",
        },
        "book5" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/book_h.png",
            "class" : "book_h",
            "left": "2440px",
            "top": "795px",
            "width": "100px",
            "height": "80px",
        },
        "book6" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/book_h.png",
            "class" : "book_h",
            "left": "2440px",
            "top": "690px",
            "width": "100px",
            "height": "80px",
        },

        // <!-- tech equipments -->
        "super_computer" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/super_computer.png",
            "class" : "tech",
            "left": "520px",
            "top": "889px",
            "width": "205px",
            "height": "205px",
        },
        "gpu1" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/gpu.png",
            "class" : "gpu",
            "left": "770px",
            "top": "880px",
            "width": "64.66px",
            "height": "78px",
        },
        "gpu2" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/gpu.png",
            "class" : "gpu",
            "left": "875px",
            "top": "880px",
            "width": "64.66px",
            "height": "78px",
        },
        "gpu3" : {
            "walkable" : false, 
            "data-response" : "",
            "src" : "/public/pokemon_resources/gpu.png",
            "class" : "gpu",
            "left": "770px",
            "top": "1000px",
            "width": "64.66px",
            "height": "78px",
        },
        "gpu4" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/gpu.png",
            "class" : "gpu",
            "left": "875px",
            "top": "1000px",
            "width": "64.66px",
            "height": "78px",
        },

        // <!-- furnitures -->
        "table_monitor" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/table_monitor.png",
            "class" : "table_monitor",
            "left": "850px",
            "top": "470px",
            "width": "120px",
            "height": "310px",
        },
        "tv" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/tv.png",
            "class" : "tv",
            "left": "2050px",
            "top": "370px",
            "width": "100px",
            "height": "135px",
        },
        "architect_table" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/architect_table.gif",
            "class" : "architect_table",
            "left": "2060px",
            "top": "580px",
            "width": "163px",
            "height": "163px",
        },
        "right_sofa" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/right_sofa.gif",
            "class" : "right_sofa",
            "left": "1875px",
            "top": "535px",
            "width": "230px",
            "height": "110px",
        },
        "stool" : {
            "walkable" : false,
            "data-response" : "",
            "src" : "/public/pokemon_resources/stool.gif",
            "class" : "stool",
            "left": "752px",
            "top": "519px",
            "width": "78px",
            "height": "78px",
        },

    };